### ISSUE TITLE
Does protobuf 2.6.1 supported?

### ISSUE THREAD

**Issue by virl** [mingchen/protobuf-ios#10]
Does this lib supports protobuf 2.6.1?
And how, if it makes its own compiler?

**Comment by mingchen** [comment]
Protobuf is a protocol. To test compatibility, you can try to decode your protobuf data which compiled in other compiler.

**Comment by virl** [comment]
What I mean does your lib supports latest protobuf compiler?
I used your protoc with Java and it is not compatible with last versions of protobuf support library.

**Comment by mingchen** [comment]
This project main purpose is for iOS projects to use protobuf, the target is objc.
However you still can use protoc to generate java code, but you also need generated java support library from this version's java source code. not the newer version of java protobuf library. The implementation maybe change. only the protocol not change. If you only want java code, you do not this project.

**Comment by virl** [comment]
Exactly. That's the problem: the project uses old version of protoc compiler, so if I want to use protoc for generating java sources, I have to install separate version of it. That's why today I moved to http://protobuf.io

**Comment by mingchen** [comment]
If you want java source, probably you just need official protobuf release. this project main target is objc.

**Comment by virl** [comment]
I have server in java and client in objc. Your protoc compiler is not compatible with latest java protobuf library, so it conflicts with official protobuf compiler.

**Comment by mingchen** [comment]
You can just new compiler with java code in your server side. and leave your objc code to use another objc version of protoc compiler.

**Comment by virl** [comment]
Thanks, but I'll just use protobuf.io :)
