### ISSUE TITLE
RpcServices support?

### ISSUE THREAD

**Issue by 4ntoine** [mingchen/protobuf-ios#13]
Having `services.proto` file:
```
syntax = "proto2";

option java_generic_services = true;
option java_package = "com.company.api.proto";

import "wifi.proto"; 

service InstallService {
	rpc getWifiNetworks (WifiRequest) returns (WifiResponse);
}
```

I can generate RpcService files for java, but not for obj-c:
```
MBA-Anton:proto asmirnov$ /softdev/protobuf-ios/compiler/src/protoc --objc_out=./obj-c/ ./service.proto 
service.proto:3:8: Option "java_generic_services" unknown.
```

Any similar options for objective-c? Rpc supported?

**Comment by mingchen** [comment]
No. It is not supported yet. Contribution is welcome.

**Comment by 4ntoine** [comment]
Is it closed with "fixed" or it's not supported eventually?

**Comment by mingchen** [comment]
I am sorry I don't have this requirement and I do not have plan to support it. You are welcome to contribute.
