### ISSUE TITLE
problem with ./autogen.sh and ./configure

### ISSUE THREAD

**Issue by aetsyss** [mingchen/protobuf-ios#2]
hi!
i'm trying to follow installation instructions:
cd compiler
./autogen.sh
./configure
make
make install (optional)

and got this:
192-168-1-163:compiler alextsyss$ ./autogen.sh
 sed -i -e 's/RuntimeLibrary="5"/RuntimeLibrary="3"/g;
           s/RuntimeLibrary="4"/RuntimeLibrary="2"/g;' gtest/msvc/gtest.vcproj gtest/msvc/gtest_color_test_.vcproj gtest/msvc/gtest_env_var_test_.vcproj gtest/msvc/gtest_environment_test.vcproj gtest/msvc/gtest_main.vcproj gtest/msvc/gtest_output_test_.vcproj gtest/msvc/gtest_prod_test.vcproj gtest/msvc/gtest_uninitialized_test_.vcproj gtest/msvc/gtest_unittest.vcproj
 autoreconf -f -i -Wall,no-obsolete

./autogen.sh: line 28: autoreconf: command not found

192-168-1-163:compiler alextsyss$ ./configure
-bash: ./configure: No such file or directory

192-168-1-163:compiler alextsyss$ make
make: **\* No rule to make target `m4/libtool.m4', needed by`Makefile.in'.  Stop.

192-168-1-163:compiler alextsyss$ make install
make: **\* No rule to make target `m4/libtool.m4', needed by`Makefile.in'.  Stop.

192-168-1-163:compiler alextsyss$

what am I doing wrong?

**Comment by shushaoyefeng** [comment]
I have already installed the automake.

here is my log"
------------------------------------------------------------------------------------
APPLEdeMBP:~ Lynn$ sudo brew install automake
Password:
Warning: automake-1.15 already installed
APPLEdeMBP:~ Lynn$ 
------------------------------------------------------------------------------------

**Comment by yonathantilahun** [comment]
Excellent!!

**Comment by hellohelloye** [comment]
yum install automake 

works for me

**Comment by 32bitbradley** [comment]
Thanks :)
