### ISSUE TITLE
How can I generate ARC classes using protoc

### ISSUE THREAD

**Issue by lomaverde** [mingchen/protobuf-ios#6]
I have added protobuf-ios to my project but I notices the classes generated using protoc is not ARC classes.  Is there an option to generate ARC classes?

**Comment by mingchen** [comment]
No. ARC and non-ARC code can mix together.
If you like to implement it that would be great.

**Comment by lomaverde** [comment]
I would love to contribute when I get some free time.

**Comment by mingchen** [comment]
Thank you.
