### ISSUE TITLE
[Solved] A lot of errors

### ISSUE THREAD

**Issue by zhangtemplar** [mingchen/protobuf-ios#8]
After I add your library to Xcode via cocoa pods, a lot of error immediately happens:
1, Can not find explicit declaration of interface NSObject;
after some search around, this one can be solved by via adding "import "UIKit/UIKit.h" to the .h file generated by photobuf compiler;

2, Your library is NOT built for automatic reference counting!!!
Sorry, this issue can be solved by adding compile flag "-fno-objc-arc" to *.m files generated by the protobuf compiler. In Xcode, select the main project/targets/build phases/compile sources/select the m files/double click under compiler flag/add "-fno-objc-arc" to the popped window.

**Comment by mingchen** [comment]
1. There is nothing related UI. So should not include UIKit.h
2. I have no plan to make generate ARC code. ARC code and none ARC code can work together.

**Comment by zhangtemplar** [comment]
@mingchen that's wired, if I don't use "#import "UIKit/UIKit.h", then there will be errors as I mentioned above.

ARC issue is now solved.

**Comment by mingchen** [comment]
Thank you for non-arc setting. I also update README to note generated code  is non-ARC.

**Comment by zhangtemplar** [comment]
@mingchen you are more than welcomed.
